# Generated by Django 3.2.16 on 2024-02-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_auto_20240227_1813"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
